### ISSUE TITLE
Missing Glasses for Shared LUA

### ISSUE THREAD

**Issue by d-w00d** [lilphantom25/qb-cyberbarjob#1]
Glasses are missing for Pint Small Etc Images are there for images but not for shared LUA Setup on how to install for people :) Love the idea!

**Comment by lilphantom25** [comment]
> Glasses are missing for Pint Small Etc Images are there for images but not for shared LUA Setup on how to install for people :) Love the idea!

My bad, sorry, have added the glasses in to the readme.md, thanks for pointing it out :)
